name: hotel management system
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5  

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run:  python manage.py migrate

      # - name: Deploy django to heroku
      #   env:
      #     HEROKU_APP_NAME : ${{ secrets.HEROKU_APP_NAME }}
      #     HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_APP_EMAIL: ${{ secrets.HEROKU_APP_EMAIL }}
      #   if: github.ref == 'refs/heads/main' && job.status == 'success'
      #   run: |
      #       git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
      #       git push heroku HEAD:main -f

      # to be added when project code is complete and refactored
        # flake8
        


      


        
    



  

         
