name: django_girls
on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Django-girls

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5  

    steps:
      - uses: actions/checkout@v1

      - name: Get all environment variable
        run: |
            echo 'I am in the Django-girls environment'

      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: psycopg2 prerequisites
        run: sudo apt-get install libpq-dev
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run migrations

        env:
        SECRET_KEY: ${{ secrets.SECRET_KEY}}
        DEBUG: ${{ secrets.DEBUG }}
        ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS}}
        DB_NAME: ${{ secrets.DB_NAME}}
        DB_USER: ${{ secrets.DB_USER}}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD}}
        DB_HOST: ${{ secrets.DB_HOST}}
        DB_PORT: ${{ secrets.DB_PORT}}

        DB_GITHUB_NAME: ${{ secrets.DB_GITHUB_NAME}}
        DB_GITHUB_USER: ${{ secrets.DB_GITHUB_USER}}
        DB_GITHUB_PASSWORD: ${{ secrets.DB_GITHUB_PASSWORD}}
        DB_GITHUB_HOST: ${{ secrets.DB_GITHUB_HOST}}
        DB_GITHUB_PORT: ${{ secrets.DB_GITHUB_PORT}}

        run:  python manage.py migrate

      # - name: Deploy django to heroku
      #   env:
      #     HEROKU_APP_NAME : ${{ secrets.HEROKU_APP_NAME }}
      #     HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_KEY }}
      #     HEROKU_APP_EMAIL: ${{ secrets.HEROKU_APP_EMAIL }}
      #   if: github.ref == 'refs/heads/main' && job.status == 'success'
      #   run: |
      #       git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
      #       git push heroku HEAD:main -f

      # to be added when project code is complete and refactored
        # flake8
        


      


        
    



  

         
